### ISSUE TITLE
v2_tx_live_player.dart 中 destroy方法貌似有点问题

### ISSUE THREAD

**Issue by brandoneedyou** [LiteAVSDK/Live_Flutter#10]
源码中方法如下：

void destroy() {
    _listeners.removeAll;
    TXLiveManager.destroyPlayer(_identifier);
  }

是否 _listeners.removeAll; 应该修改为  _listeners.clear();  ?

**Comment by AbySwifter** [comment]
已反馈对应同学处理

**Comment by githubliuqi** [comment]
已修复
