### ISSUE TITLE
请增加关闭log日志的功能

### ISSUE THREAD

**Issue by WhiteorBlack** [LiteAVSDK/Live_Flutter#11]

**Comment by AbderraoufKhodja** [comment]
Same problem here. Too many logs.

**Comment by One-time** [comment]
Please use `V2TXLivePremier.setLogConfig()` to set.
Example:
`var logConfig = V2TXLiveLogConfig();`
`logConfig.logLevel = V2TXLiveLogLevel.v2TXLiveLogLevelNULL;`
`V2TXLivePremier.setLogConfig(logConfig);`
