### ISSUE TITLE
初始化和调用同时可能导致MissingPluginException

### ISSUE THREAD

**Issue by ymback** [LiteAVSDK/Live_Flutter#18]
V2TXLivePusher初始化时调用_createNativePusher与原生端绑定，因为没有await，导致可能在初始化后直接调用需要invokeMethod的函数报MissingPluginException
Player同理

**Comment by ymback** [comment]
所以这事要么各位用这个的开发换个写法比较稳妥，毕竟列表里的时候出这事挺尴尬的

**Comment by AbySwifter** [comment]
已反馈处理

**Comment by githubliuqi** [comment]
已修复
