### ISSUE TITLE
连麦mixStreams空指针

### ISSUE THREAD

**Issue by ymback** [LiteAVSDK/Live_Flutter#19]
安卓端，连麦setMixTranscodingConfig，config通过693行函数getMixTranscodingConfigByMap转换，mixStreams读取在726行，未考虑空的情况，导致设置后在安卓端直播SDK中，V2TXLivePusherJni类的403行设置的时候，在423行直接读取var5.size()空指针，CRASH

**Comment by ymback** [comment]
行了，我知道了，空指针就算了，主要问题是getMixTranscodingConfigByMap的时候为什么一定要初始化一个值，明明取消连麦要传入null，你初始化了，视频流都没法回到单个，然后下面mixStreams还空，直接crash

**Comment by AbySwifter** [comment]
已安排跟进
