### ISSUE TITLE
无论播放还是推流，时间长了之后手机发烫严重

### ISSUE THREAD

**Issue by ymback** [LiteAVSDK/Live_Flutter#20]
拿DEMO跑，十几分钟开始后盖就热起来了，一小时之后烫了，iPhone更严重一点

**Comment by ymback** [comment]
UI层去除V2TXLiveVideoWidget或者V2TXLiveVideoWidget后发热情况就消失了，看来还是PlatformView渲染机制的问题啊

**Comment by AbySwifter** [comment]
感谢反馈，这个问题我们也会关注Flutter的版本迭代来升级优化
