### ISSUE TITLE
ios模拟器上运行一直报错Framework not found TXFFmpeg

### ISSUE THREAD

**Issue by Tianyazz** [LiteAVSDK/Live_Flutter#27]
之前是好的，不知道是啥原因，今天突然不行了，找了好多办法，一直不行。升级了版本也是一样
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/1g/fvwnmlyd3vdgbc4wdn261wnc0000gn/T/flutter_tools.IM32cA/flutter_ios_build_temp_dirS8atXd/temporary_xcresult_bundle

    warning: [CP] TXSoundTouch.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform
    (-iphonesimulator).
    warning: [CP] TXFFmpeg.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:770:17: warning: parameters of 'onError(_:message:extraInfo:)' have different
    optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onError(_ code: V2TXLiveCode, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:2:19: note: requirement 'onError(_:message:extraInfo:)' declared here
        optional func onError(_ code: V2TXLiveCode, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:775:17: warning: parameters of 'onWarning(_:message:extraInfo:)' have different
    optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onWarning(_ code: V2TXLiveCode, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                  ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:3:19: note: requirement 'onWarning(_:message:extraInfo:)' declared here
        optional func onWarning(_ code: V2TXLiveCode, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:795:17: warning: parameters of 'onPushStatusUpdate(_:message:extraInfo:)' have
    different optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onPushStatusUpdate(_ status: V2TXLivePushStatus, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                                   ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:7:19: note: requirement 'onPushStatusUpdate(_:message:extraInfo:)' declared here
        optional func onPushStatusUpdate(_ status: V2TXLivePushStatus, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:800:17: warning: parameter of 'onStatisticsUpdate' has different optionality
    than expected by protocol 'V2TXLivePusherObserver'
        public func onStatisticsUpdate(_ statistics: V2TXLivePusherStatistics!) {
                    ^                                                        ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:8:19: note: requirement 'onStatisticsUpdate' declared here
        optional func onStatisticsUpdate(_ statistics: V2TXLivePusherStatistics)
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:813:17: warning: parameter of 'onSnapshotComplete' has different optionality
    than expected by protocol 'V2TXLivePusherObserver'
        public func onSnapshotComplete(_ image: UIImage!) {
                    ^                                  ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:10:19: note: requirement 'onSnapshotComplete' declared here
        optional func onSnapshotComplete(_ image: UIImage)
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/View/V2LiveRenderView.swift:57:9: warning: default will never be executed
            default:
            ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/TXDeviceManagerPlugin.swift:98:34: warning: 'setSystemVolumeType' is deprecated: use
    TRTCCloud#startLocalAudio:quality instead
            let code = deviceManager.setSystemVolumeType(type)
                                     ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/TXLiteAVSDK.h"
            ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/TXDeviceManagerPlugin.swift:98:34: warning: 'setSystemVolumeType' is deprecated: use
    TRTCCloud#startLocalAudio:quality instead
            let code = deviceManager.setSystemVolumeType(type)
                                     ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:770:17: warning: parameters of 'onError(_:message:extraInfo:)' have different
    optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onError(_ code: V2TXLiveCode, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:2:19: note: requirement 'onError(_:message:extraInfo:)' declared here
        optional func onError(_ code: V2TXLiveCode, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:775:17: warning: parameters of 'onWarning(_:message:extraInfo:)' have different
    optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onWarning(_ code: V2TXLiveCode, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                  ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:3:19: note: requirement 'onWarning(_:message:extraInfo:)' declared here
        optional func onWarning(_ code: V2TXLiveCode, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:795:17: warning: parameters of 'onPushStatusUpdate(_:message:extraInfo:)' have
    different optionality than expected by protocol 'V2TXLivePusherObserver'
        public func onPushStatusUpdate(_ status: V2TXLivePushStatus, message msg: String!, extraInfo: [AnyHashable : Any]!) {
                    ^                                                                   ~                                ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:7:19: note: requirement 'onPushStatusUpdate(_:message:extraInfo:)' declared here
        optional func onPushStatusUpdate(_ status: V2TXLivePushStatus, message msg: String, extraInfo: [AnyHashable : Any])
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:800:17: warning: parameter of 'onStatisticsUpdate' has different optionality
    than expected by protocol 'V2TXLivePusherObserver'
        public func onStatisticsUpdate(_ statistics: V2TXLivePusherStatistics!) {
                    ^                                                        ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:8:19: note: requirement 'onStatisticsUpdate' declared here
        optional func onStatisticsUpdate(_ statistics: V2TXLivePusherStatistics)
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/Plugin/V2TXLivePusherPlugin.swift:813:17: warning: parameter of 'onSnapshotComplete' has different optionality
    than expected by protocol 'V2TXLivePusherObserver'
        public func onSnapshotComplete(_ image: UIImage!) {
                    ^                                  ~

    TXLiteAVSDK_Professional.V2TXLivePusherObserver:10:19: note: requirement 'onSnapshotComplete' declared here
        optional func onSnapshotComplete(_ image: UIImage)
                      ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/live_flutter_plugin-1.0.7/ios/Classes/View/V2LiveRenderView.swift:57:9: warning: default will never be executed
            default:
            ^
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/ReachabilityConnectivityProvider.swift:23:5: warning: result of call to 'ensureReachability()' is unused
        ensureReachability()
        ^                 ~~
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/PathMonitorConnectivityProvider.swift:31:5: warning: result of call to 'ensurePathMonitor()' is unused
        ensurePathMonitor()
        ^                ~~
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/PathMonitorConnectivityProvider.swift:35:5: warning: result of call to 'ensurePathMonitor()' is unused
        ensurePathMonitor()
        ^                ~~
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/ReachabilityConnectivityProvider.swift:23:5: warning: result of call to 'ensureReachability()' is unused
        ensureReachability()
        ^                 ~~
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/PathMonitorConnectivityProvider.swift:31:5: warning: result of call to 'ensurePathMonitor()' is unused
        ensurePathMonitor()
        ^                ~~
    /Users/end/.pub-cache/hosted/pub.flutter-io.cn/connectivity_plus-2.3.5/ios/Classes/PathMonitorConnectivityProvider.swift:35:5: warning: result of call to 'ensurePathMonitor()' is unused
        ensurePathMonitor()
        ^                ~~
    ld: framework not found TXFFmpeg
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

    Result bundle written to path:
    	/var/folders/1g/fvwnmlyd3vdgbc4wdn261wnc0000gn/T/flutter_tools.IM32cA/flutter_ios_build_temp_dirS8atXd/temporary_xcresult_bundle

Error (Xcode): Framework not found TXFFmpeg

Could not build the application for the simulator.
Error launching application on iPod touch (7th generation).

**Comment by kira2015** [comment]
我也遇到,貌似只能够真机运行?

**Comment by HongZhiQing** [comment]
我也遇到一样的问题，有解决办法吗

**Comment by Linzehua2015** [comment]
@kira2015  @HongZhiQing    xcode里饮用这两个库即可  
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15622568/187404665-695b7911-7c98-4988-ae90-c51caf415f47.png">

**Comment by kira2015** [comment]
> @Linzehua2015 感激,帮大忙了
