### ISSUE TITLE
请更新uuid这个引用库

### ISSUE THREAD

**Issue by M2dL1fe** [LiteAVSDK/Live_Flutter#44]
![image](https://github.com/LiteAVSDK/Live_Flutter/assets/8074125/d42eed8d-561c-41ff-988d-0df8bc1d04a3)

![image](https://github.com/LiteAVSDK/Live_Flutter/assets/8074125/0da1a33e-d6db-42cd-841d-12f69703e935)

**Comment by M2dL1fe** [comment]
能不能来个人更新一下这两个引用库啊，请将你们的引用库一直保持最新啊。。。

**Comment by saviourdog** [comment]
+1

**Comment by M2dL1fe** [comment]
```
dependency_overrides:
  uuid: ^4.3.3
```
可以暂时这样来处理，但最好的做法，还是官方更新 @saviourdog

**Comment by M2dL1fe** [comment]
11.7.1 终于舍得升级，而且这里根本没人管
